# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8SDT0-5kE-OJik3jlpZC5JlkAe6dtLE
"""

def compute_failure_function(pattern):
    """
    Computes the failure function f(s) for a given pattern.
    f(s) = length of the longest proper prefix of pattern[0:s]
           that is also a suffix of pattern[0:s]
    """
    n = len(pattern)
    f = [0] * n  # failure function array
    t = 0        # length of previous longest prefix suffix

    for s in range(1, n):
        while t > 0 and pattern[s] != pattern[t]:
            t = f[t - 1]

        if pattern[s] == pattern[t]:
            t += 1
            f[s] = t
        else:
            f[s] = 0

    return f



# Ejercicio 3.4.5

patterns = [
    "abababaab",
    "aaaaaa",
    "abbaabb"
]

for p in patterns:
    print("Pattern:", p)
    print("Failure Function:", compute_failure_function(p))
    print()